:recycle: move frontend Dockerfile to multistage with targets development, build and build-deploy

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -15,10 +15,6 @@ ENV APP ${APP}
 ENV APP_VERSION ${app_ver}
 
 WORKDIR /$app_path
-VOLUME /$app_path/src
-VOLUME /$app_path/build
-VOLUME /$app_path/config
-VOLUME /$app_path/dist
 
 # update debian w/proxy & mirror
 RUN echo "$http_proxy $no_proxy" && set -x && [ -z "$MIRROR_DEBIAN" ] || \
@@ -51,6 +47,23 @@ RUN npm audit fix --registry=https://registry.npmjs.org
 # Step 2: "development" target #
 ################################
 FROM base as development
+ARG http_proxy
+ARG https_proxy
+ARG no_proxy
+ARG npm_registry
+ARG sass_registry
+ARG MIRROR_DEBIAN
+ARG app_path
+ARG app_name
+ARG app_ver
+ENV APP ${APP}
+ENV APP_VERSION ${app_ver}
+
+VOLUME /$app_path/src
+VOLUME /$app_path/build
+VOLUME /$app_path/config
+VOLUME /$app_path/dist
+
 EXPOSE 8080
 CMD ["npm","run","dev"]
 
@@ -58,15 +71,49 @@ CMD ["npm","run","dev"]
 # Step 3:   "build" target     #
 ################################
 FROM base as build
+ARG http_proxy
+ARG https_proxy
+ARG no_proxy
+ARG npm_registry
+ARG sass_registry
+ARG MIRROR_DEBIAN
+ARG app_path
+ARG app_name
+ARG app_ver
+ENV APP ${APP}
+ENV APP_VERSION ${app_ver}
+
+VOLUME /$app_path/dist
+
 COPY index.html ./
 COPY .babelrc .editorconfig .eslintignore .eslintrc.js ./
-COPY ${APP}Config ${APP}Config
 COPY src src
 COPY config config
 COPY build build
 COPY static static
 
-RUN mkdir -p dist/ && rm -rf dist/ && mkdir -p dist/
+CMD ["npm","run","build"]
 
-RUN npm run build
+################################
+# Step 4:"build-deploy" target #
+################################
+FROM base as build-deploy
+ARG http_proxy
+ARG https_proxy
+ARG no_proxy
+ARG npm_registry
+ARG sass_registry
+ARG MIRROR_DEBIAN
+ARG app_path
+ARG app_name
+ARG app_ver
+ENV APP ${APP}
+ENV APP_VERSION ${app_ver}
 
+COPY ${app_name}-${app_ver}-frontend.tar.gz .
+
+RUN  set -ex ; tar -zxvf ${app_name}-${app_ver}-frontend.tar.gz  && \
+     npm run build 2>&1 | tee npm.log; egrep -E '(ERROR|error)' npm.log && exit 1 ; rm -rf npm.log \
+     rm -rf /${app_name}-${app_ver}-frontend.tar.gz
+
+CMD ["npm","run","build"]
